version: "3.7"

services:
  java-gradle:
    build: ./java/java-gradle
  java-maven:
    build: ./java/java-maven

  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8080:80"
