version: "3.7" 

services:
    go:
        build: ./go
 
    typescript:
        build: ./typescript

    dotnet:
        build: ./dotnet        

    nginx:
      image: "nginx:latest"
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      ports:
        - "8080:80"
